language: go
install:
- sudo add-apt-repository -y ppa:masterminds/glide
- sudo apt-get update
- sudo apt-get -y install glide
- glide update -v
matrix:
  include:
  - go: 1.x
    env: OPTIONS="-race"
  - go: 1.x
    env: COVERAGE="true" OPTIONS=""
script:
- go fmt $(go list ./... | grep -v vendor) | wc -l | grep 0
- go vet $(go list ./... | grep -v vendor)
- go test $OPTIONS $(go list ./... | grep -v vendor)
